import = [
  "~/.config/alacritty/themes/themes/hardhacker.toml"
]
[window]
padding.x = 10
padding.y = 10
decorations = "Buttonless"
opacity = 0.8
blur = true
option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"
size = 14

[keyboard]
bindings = [
 { key = "Right", mods = "Alt", chars = "\u001BF"},
 { key = "Left", mods = "Alt", chars = "\u001BB"},
]
